services:

  # Database (Postgres)

  connector-postgres:
    image: postgres:18.1-alpine3.23
    container_name: connector-postgres
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB_NAME:-edc_store}
    networks:
      - weforming_connector_network
    volumes: 
      - connector-postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Connector (Connector + Identity Hub + Launcher)

  weforming-connector:
    hostname: connector
    image: ${CONNECTOR_IMAGE:-weforming-connector}
    build:
      context: ./source
    restart: unless-stopped
    depends_on:
      connector-postgres:
        condition: service_healthy
    ports:
      - '${CONNECTOR_PORT_BASE:-8001}:${CONNECTOR_PORT_BASE:-8001}'
      - '${CONNECTOR_PORT_PUBLIC:-8002}:${CONNECTOR_PORT_PUBLIC:-8002}'
      - '${CONNECTOR_PORT_CONTROL:-8003}:${CONNECTOR_PORT_CONTROL:-8003}'
      - '${CONNECTOR_PORT_MANAGEMENT:-8004}:${CONNECTOR_PORT_MANAGEMENT:-8004}'
      - '${CONNECTOR_PORT_PROTOCOL:-8005}:${CONNECTOR_PORT_PROTOCOL:-8005}'
      - '${IH_PORT_BASE:-7001}:${IH_PORT_BASE:-7001}'
      - '${IH_PORT_CREDENTIALS:-7002}:${IH_PORT_CREDENTIALS:-7002}'
      - '${IH_PORT_IDENTITY:-7003}:${IH_PORT_IDENTITY:-7003}'
      - '${IH_PORT_DID:-7004}:${IH_PORT_DID:-7004}'
      - '${IH_PORT_VERSION:-7005}:${IH_PORT_VERSION:-7005}'
      - '${IH_PORT_STS:-7006}:${IH_PORT_STS:-7006}'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - weforming_connector_network
    volumes:
      - ./test-keys:/keys:ro
      - ./credentials:/credentials:ro
    environment:
      # Log level

      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # Java

      - JAVA_RUNTIME_FLAGS_CONNECTOR=${JAVA_RUNTIME_FLAGS_CONNECTOR:-}
      - JAVA_RUNTIME_FLAGS_IH=${JAVA_RUNTIME_FLAGS_IH:-}

      # Identity

      - PARTICIPANT_ID=${REGISTER_PARTICIPANT_PARTICIPANT_DID}

      # Identity proxy

      - IDENTITY_PROXY_URL=${IDENTITY_PROXY_URL}
      - IDENTITY_PROXY_TOKEN=${IDENTITY_PROXY_TOKEN}

      # Credentials

      - VC_FOLDER=/credentials
      - TRUSTED_ISSUERS=${TRUSTED_ISSUERS:-}

      # Keys

      - PUBLIC_KEY=/keys/${CONNECTOR_PUBLIC_KEY_FILE:-connector-public.pem}
      - PRIVATE_KEY=/keys/${CONNECTOR_PRIVATE_KEY_FILE:-connector-private.pem}
      - DID_PUBLIC_KEY_TYPE=${DID_PUBLIC_KEY_TYPE:-Ed25519VerificationKey2018}

      # Wallet private key

      - DID_OWNER_PRIVATE_KEY=${WALLET_PRIVATE_KEY}

      # Ports (connector)

      - CONNECTOR_PORT_BASE=${CONNECTOR_PORT_BASE:-8001}
      - CONNECTOR_PORT_PUBLIC=${CONNECTOR_PORT_PUBLIC:-8002}
      - CONNECTOR_PORT_CONTROL=${CONNECTOR_PORT_CONTROL:-8003}
      - CONNECTOR_PORT_MANAGEMENT=${CONNECTOR_PORT_MANAGEMENT:-8004}
      - CONNECTOR_PORT_PROTOCOL=${CONNECTOR_PORT_PROTOCOL:-8005}

      # Ports (Identity Hub)

      - IH_PORT_BASE=${IH_PORT_BASE:-7001}
      - IH_PORT_CREDENTIALS=${IH_PORT_CREDENTIALS:-7002}
      - IH_PORT_IDENTITY=${IH_PORT_IDENTITY:-7003}
      - IH_PORT_DID=${IH_PORT_DID:-7004}
      - IH_PORT_VERSION=${IH_PORT_VERSION:-7005}
      - IH_PORT_STS=${IH_PORT_STS:-7006}

      # External URLs

      - CREDENTIAL_SERVICE_EXTERNAL_URL=${CREDENTIAL_SERVICE_EXTERNAL_URL:-http://localhost:7002}
      - PROTOCOL_EXTERNAL_URL=${PROTOCOL_EXTERNAL_URL:-http://localhost:8005}

      # Postgres

      - POSTGRES_HOST=${POSTGRES_HOST:-connector-postgres}
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-edc_store}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

      # Other secrets

      - IH_SUPER_USER_SECRET=${IH_SUPER_USER_SECRET:-super-secret-key}

  # Dozzle (Container log viewer)

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    ports:
      - "${DOZZLE_PORT:-9999}:8080"
    networks:
      - weforming_connector_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Networks

networks:
  weforming_connector_network:
    name: wf_connector_net
    driver: bridge

# Volumes

volumes:
  connector-postgres:
    driver: local
