/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/catalog': typeof CatalogRoute
  '/contracts': typeof ContractsRoute
  '/participants': typeof ParticipantsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/catalog': typeof CatalogRoute
  '/contracts': typeof ContractsRoute
  '/participants': typeof ParticipantsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/catalog': typeof CatalogRoute
  '/contracts': typeof ContractsRoute
  '/participants': typeof ParticipantsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/assets'
    | '/catalog'
    | '/contracts'
    | '/participants'
    | '/policies'
    | '/settings'
    | '/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/assets'
    | '/catalog'
    | '/contracts'
    | '/participants'
    | '/policies'
    | '/settings'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics'
    | '/assets'
    | '/catalog'
    | '/contracts'
    | '/participants'
    | '/policies'
    | '/settings'
    | '/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  CatalogRoute: typeof CatalogRoute
  ContractsRoute: typeof ContractsRoute
  ParticipantsRoute: typeof ParticipantsRoute
  PoliciesRoute: typeof PoliciesRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  CatalogRoute: CatalogRoute,
  ContractsRoute: ContractsRoute,
  ParticipantsRoute: ParticipantsRoute,
  PoliciesRoute: PoliciesRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
