/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatusRouteRouteImport } from './routes/status/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StatusRequestsRouteImport } from './routes/status/requests'
import { Route as StatusCredentialsRouteImport } from './routes/status/credentials'
import { Route as StatusAuditRouteImport } from './routes/status/audit'
import { Route as AdminRevokeRouteImport } from './routes/admin/revoke'
import { Route as AdminResolvedRouteImport } from './routes/admin/resolved'
import { Route as AdminIncomingRouteImport } from './routes/admin/incoming'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRouteRoute = StatusRouteRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatusRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StatusRequestsRoute = StatusRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => StatusRouteRoute,
} as any)
const StatusCredentialsRoute = StatusCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => StatusRouteRoute,
} as any)
const StatusAuditRoute = StatusAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StatusRouteRoute,
} as any)
const AdminRevokeRoute = AdminRevokeRouteImport.update({
  id: '/revoke',
  path: '/revoke',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResolvedRoute = AdminResolvedRouteImport.update({
  id: '/resolved',
  path: '/resolved',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIncomingRoute = AdminIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/status': typeof StatusRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wizard': typeof WizardRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/incoming': typeof AdminIncomingRoute
  '/admin/resolved': typeof AdminResolvedRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/status/audit': typeof StatusAuditRoute
  '/status/credentials': typeof StatusCredentialsRoute
  '/status/requests': typeof StatusRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/status/': typeof StatusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wizard': typeof WizardRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/incoming': typeof AdminIncomingRoute
  '/admin/resolved': typeof AdminResolvedRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/status/audit': typeof StatusAuditRoute
  '/status/credentials': typeof StatusCredentialsRoute
  '/status/requests': typeof StatusRequestsRoute
  '/admin': typeof AdminIndexRoute
  '/status': typeof StatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/status': typeof StatusRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wizard': typeof WizardRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/incoming': typeof AdminIncomingRoute
  '/admin/resolved': typeof AdminResolvedRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/status/audit': typeof StatusAuditRoute
  '/status/credentials': typeof StatusCredentialsRoute
  '/status/requests': typeof StatusRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/status/': typeof StatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/status'
    | '/settings'
    | '/wizard'
    | '/admin/credentials'
    | '/admin/incoming'
    | '/admin/resolved'
    | '/admin/revoke'
    | '/status/audit'
    | '/status/credentials'
    | '/status/requests'
    | '/admin/'
    | '/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/wizard'
    | '/admin/credentials'
    | '/admin/incoming'
    | '/admin/resolved'
    | '/admin/revoke'
    | '/status/audit'
    | '/status/credentials'
    | '/status/requests'
    | '/admin'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/status'
    | '/settings'
    | '/wizard'
    | '/admin/credentials'
    | '/admin/incoming'
    | '/admin/resolved'
    | '/admin/revoke'
    | '/status/audit'
    | '/status/credentials'
    | '/status/requests'
    | '/admin/'
    | '/status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StatusRouteRoute: typeof StatusRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WizardRoute: typeof WizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof StatusRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/status/requests': {
      id: '/status/requests'
      path: '/requests'
      fullPath: '/status/requests'
      preLoaderRoute: typeof StatusRequestsRouteImport
      parentRoute: typeof StatusRouteRoute
    }
    '/status/credentials': {
      id: '/status/credentials'
      path: '/credentials'
      fullPath: '/status/credentials'
      preLoaderRoute: typeof StatusCredentialsRouteImport
      parentRoute: typeof StatusRouteRoute
    }
    '/status/audit': {
      id: '/status/audit'
      path: '/audit'
      fullPath: '/status/audit'
      preLoaderRoute: typeof StatusAuditRouteImport
      parentRoute: typeof StatusRouteRoute
    }
    '/admin/revoke': {
      id: '/admin/revoke'
      path: '/revoke'
      fullPath: '/admin/revoke'
      preLoaderRoute: typeof AdminRevokeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resolved': {
      id: '/admin/resolved'
      path: '/resolved'
      fullPath: '/admin/resolved'
      preLoaderRoute: typeof AdminResolvedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/incoming': {
      id: '/admin/incoming'
      path: '/incoming'
      fullPath: '/admin/incoming'
      preLoaderRoute: typeof AdminIncomingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminIncomingRoute: typeof AdminIncomingRoute
  AdminResolvedRoute: typeof AdminResolvedRoute
  AdminRevokeRoute: typeof AdminRevokeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminIncomingRoute: AdminIncomingRoute,
  AdminResolvedRoute: AdminResolvedRoute,
  AdminRevokeRoute: AdminRevokeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StatusRouteRouteChildren {
  StatusAuditRoute: typeof StatusAuditRoute
  StatusCredentialsRoute: typeof StatusCredentialsRoute
  StatusRequestsRoute: typeof StatusRequestsRoute
  StatusIndexRoute: typeof StatusIndexRoute
}

const StatusRouteRouteChildren: StatusRouteRouteChildren = {
  StatusAuditRoute: StatusAuditRoute,
  StatusCredentialsRoute: StatusCredentialsRoute,
  StatusRequestsRoute: StatusRequestsRoute,
  StatusIndexRoute: StatusIndexRoute,
}

const StatusRouteRouteWithChildren = StatusRouteRoute._addFileChildren(
  StatusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StatusRouteRoute: StatusRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WizardRoute: WizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
